/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SelectRoleRouteImport } from './routes/select-role'
import { Route as BuyerBrowseRouteImport } from './routes/buyer.browse'
import { Route as BuyerDashboardRouteImport } from './routes/buyer.dashboard'
import { Route as SellerDashboardRouteImport } from './routes/seller.dashboard'
import { Route as SellerMyListingsRouteImport } from './routes/seller.my-listings'
import { Route as SellerOrdersRouteImport } from './routes/seller.orders'
import { Route as SellerProfileRouteImport } from './routes/seller.profile'
import { Route as SellerSalesRouteImport } from './routes/seller.sales'
import { Route as SellerSellProduceRouteImport } from './routes/seller.sell-produce'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectRoleRoute = SelectRoleRouteImport.update({
  id: '/select-role',
  path: '/select-role',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerBrowseRoute = BuyerBrowseRouteImport.update({
  id: '/buyer/browse',
  path: '/buyer/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerDashboardRoute = BuyerDashboardRouteImport.update({
  id: '/buyer/dashboard',
  path: '/buyer/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerDashboardRoute = SellerDashboardRouteImport.update({
  id: '/seller/dashboard',
  path: '/seller/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerMyListingsRoute = SellerMyListingsRouteImport.update({
  id: '/seller/my-listings',
  path: '/seller/my-listings',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerOrdersRoute = SellerOrdersRouteImport.update({
  id: '/seller/orders',
  path: '/seller/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerProfileRoute = SellerProfileRouteImport.update({
  id: '/seller/profile',
  path: '/seller/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerSalesRoute = SellerSalesRouteImport.update({
  id: '/seller/sales',
  path: '/seller/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerSellProduceRoute = SellerSellProduceRouteImport.update({
  id: '/seller/sell-produce',
  path: '/seller/sell-produce',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/select-role': typeof SelectRoleRoute
  '/buyer/browse': typeof BuyerBrowseRoute
  '/buyer/dashboard': typeof BuyerDashboardRoute
  '/seller/dashboard': typeof SellerDashboardRoute
  '/seller/my-listings': typeof SellerMyListingsRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/profile': typeof SellerProfileRoute
  '/seller/sales': typeof SellerSalesRoute
  '/seller/sell-produce': typeof SellerSellProduceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/select-role': typeof SelectRoleRoute
  '/buyer/browse': typeof BuyerBrowseRoute
  '/buyer/dashboard': typeof BuyerDashboardRoute
  '/seller/dashboard': typeof SellerDashboardRoute
  '/seller/my-listings': typeof SellerMyListingsRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/profile': typeof SellerProfileRoute
  '/seller/sales': typeof SellerSalesRoute
  '/seller/sell-produce': typeof SellerSellProduceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/select-role': typeof SelectRoleRoute
  '/buyer/browse': typeof BuyerBrowseRoute
  '/buyer/dashboard': typeof BuyerDashboardRoute
  '/seller/dashboard': typeof SellerDashboardRoute
  '/seller/my-listings': typeof SellerMyListingsRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/profile': typeof SellerProfileRoute
  '/seller/sales': typeof SellerSalesRoute
  '/seller/sell-produce': typeof SellerSellProduceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/select-role'
    | '/buyer/browse'
    | '/buyer/dashboard'
    | '/seller/dashboard'
    | '/seller/my-listings'
    | '/seller/orders'
    | '/seller/profile'
    | '/seller/sales'
    | '/seller/sell-produce'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/select-role'
    | '/buyer/browse'
    | '/buyer/dashboard'
    | '/seller/dashboard'
    | '/seller/my-listings'
    | '/seller/orders'
    | '/seller/profile'
    | '/seller/sales'
    | '/seller/sell-produce'
  id:
    | '__root__'
    | '/'
    | '/select-role'
    | '/buyer/browse'
    | '/buyer/dashboard'
    | '/seller/dashboard'
    | '/seller/my-listings'
    | '/seller/orders'
    | '/seller/profile'
    | '/seller/sales'
    | '/seller/sell-produce'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SelectRoleRoute: typeof SelectRoleRoute
  BuyerBrowseRoute: typeof BuyerBrowseRoute
  BuyerDashboardRoute: typeof BuyerDashboardRoute
  SellerDashboardRoute: typeof SellerDashboardRoute
  SellerMyListingsRoute: typeof SellerMyListingsRoute
  SellerOrdersRoute: typeof SellerOrdersRoute
  SellerProfileRoute: typeof SellerProfileRoute
  SellerSalesRoute: typeof SellerSalesRoute
  SellerSellProduceRoute: typeof SellerSellProduceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-role': {
      id: '/select-role'
      path: '/select-role'
      fullPath: '/select-role'
      preLoaderRoute: typeof SelectRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/browse': {
      id: '/buyer/browse'
      path: '/buyer/browse'
      fullPath: '/buyer/browse'
      preLoaderRoute: typeof BuyerBrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/dashboard': {
      id: '/buyer/dashboard'
      path: '/buyer/dashboard'
      fullPath: '/buyer/dashboard'
      preLoaderRoute: typeof BuyerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/dashboard': {
      id: '/seller/dashboard'
      path: '/seller/dashboard'
      fullPath: '/seller/dashboard'
      preLoaderRoute: typeof SellerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/my-listings': {
      id: '/seller/my-listings'
      path: '/seller/my-listings'
      fullPath: '/seller/my-listings'
      preLoaderRoute: typeof SellerMyListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/orders': {
      id: '/seller/orders'
      path: '/seller/orders'
      fullPath: '/seller/orders'
      preLoaderRoute: typeof SellerOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/profile': {
      id: '/seller/profile'
      path: '/seller/profile'
      fullPath: '/seller/profile'
      preLoaderRoute: typeof SellerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/sales': {
      id: '/seller/sales'
      path: '/seller/sales'
      fullPath: '/seller/sales'
      preLoaderRoute: typeof SellerSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/sell-produce': {
      id: '/seller/sell-produce'
      path: '/seller/sell-produce'
      fullPath: '/seller/sell-produce'
      preLoaderRoute: typeof SellerSellProduceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SelectRoleRoute: SelectRoleRoute,
  BuyerBrowseRoute: BuyerBrowseRoute,
  BuyerDashboardRoute: BuyerDashboardRoute,
  SellerDashboardRoute: SellerDashboardRoute,
  SellerMyListingsRoute: SellerMyListingsRoute,
  SellerOrdersRoute: SellerOrdersRoute,
  SellerProfileRoute: SellerProfileRoute,
  SellerSalesRoute: SellerSalesRoute,
  SellerSellProduceRoute: SellerSellProduceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
